[Metadata]
; Contiene información básica de la skin.
Name=CheClimatico
Author=masterofobzene
Information=Fork de "authentic weather" arreglado y argentinizado.
Version=1.3

[Variables]
lang=clean
; Obtenga su clave API gratuita de https://openweathermap.org/api
APIKey=xxxxxxxxxxxxxxxxxxxx
Unit=metric
; Opciones: 'black', 'white', 'blue'
IconSet=white
; Podes encontrar tu latitud y longitud aquí, https://www.latlong.net/
Latitude=xxxxxxxxxxxxxx
Longitude=xxxxxxxxxxxxx
; URL del tiempo
URL=https://api.openweathermap.org/data/2.5/weather?lat=#Latitude#&lon=#Longitude#&units=#Unit#&appid=#APIKey#
; Ruta de iconos
IconPath=#@#icon\#IconSet#\

[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
BackgroundMode=2
SolidColor=0,0,0,1

---Measures---

[Unit]
Measure=String
String=#Unit#
RegExpSubstitute=1
Substitute="metric":"°C","imperial":"°F"

[Weather]
Measure=WebParser
URL=#URL#
UserAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
RegExp=(?siU)\{.*"weather":\[\{.*"main":(.*),.*"description":(.*),"icon":(.*)\}\].*"main":\{.*"temp":(.*),.*"feels_like":(.*),.*"temp_min":(.*),.*"temp_max":(.*),.*"pressure":(.*),.*"humidity":(.*),.*"visibility":(.*),.*"wind":\{.*"speed":(.*),.*"deg":(.*)(?:,"gust":(.*))?\}.*"clouds":\{.*"all":(.*)\}.*"dt":(.*),.*"sys":\{.*"country":(.*),.*"sunrise":(.*),.*"sunset":(.*)\}.*"timezone":(.*),.*"name":(.*),.*\}
UpdateRate=600

[Main]
Measure=WebParser
URL=[Weather]
StringIndex=1
RegExpSubstitute=1
Substitute='(?:^"|"$)':""

[IconMapping]
Measure=Script
ScriptFile=#@#icon_mapping.lua

[Icon]
Measure=WebParser
URL=[Weather]
StringIndex=3
RegExpSubstitute=1
Substitute='(?:^"|"$)':""

[Temp]
Measure=WebParser
URL=[Weather]
StringIndex=4
RegExpSubstitute=1
Substitute='(?:^"|"$)':""

[Humidity]
Measure=WebParser
URL=[Weather]
StringIndex=9
RegExpSubstitute=1
Substitute='(?:^"|"$)':""

[HumidityText]
Meter=String
X=10
Y=170
FontFace=Segoe UI
FontSize=14
FontColor=255,255,255,255
AntiAlias=1
Text=Humedad: %1%
MeasureName=Humidity

[MeasurePhraseSelector]
Measure=Script
ScriptFile=#@#phrase_selector.lua
IfCondition=1=1
IfTrueAction=[!UpdateMeasure "MeasureSelectedScript"][!UpdateMeter *][!Redraw]

---Meters---

[TempText]
Meter=String
X=125
Y=60
FontFace=Segoe UI
StringStyle=Bold
FontSize=24
FontColor=255,255,255,255
AntiAlias=1
MeasureName=RoundTemp
MeasureName2=Unit
Text=%1 %2

[IconImage]
Meter=Image
X=10
Y=20
W=100
H=80
PreserveAspectRatio=1
ImageName=#IconPath##IconMapping#
DynamicVariables=1

[PhraseText]
Meter=String
X=10
Y=110
FontFace=Segoe UI
StringStyle=Bold
FontSize=18
FontColor=255,255,255,255
AntiAlias=1
MeasureName=MeasurePhraseSelector
Text=%1
DynamicVariables=1
InlineSetting=Color | #color#
InlinePattern="(%b())"

[SublineText]
Meter=String
X=10
Y=140
FontFace=Segoe UI
FontSize=14
FontColor=255,255,255,255
AntiAlias=1
MeasureName=MeasurePhraseSelector
Text=%1
DynamicVariables=1
InlineSetting=Color | #color#
InlinePattern="(%b())"

[WarningTextAPIKey]
Meter=String
X=10
Y=170
FontFace=Segoe UI
StringStyle=Bold
FontSize=14
FontColor=255,255,255,255
AntiAlias=1
Text="Edite la API Key en la configuración de la skin."
DynamicVariables=1
Measure=#APIKey#
IfMatch=^$
IfMatchAction=[!ShowMeter WarningTextAPIKey][!Redraw]
IfNotMatchAction=[!HideMeter WarningTextAPIKey][!Redraw]

[WarningTextLatitude]
Meter=String
X=10
Y=190
FontFace=Segoe UI
StringStyle=Bold
FontSize=14
FontColor=255,255,255,255
AntiAlias=1
Text="Edite la latitud en la configuración de la skin."
DynamicVariables=1
Measure=#Latitude#
IfMatch=^$
IfMatchAction=[!ShowMeter WarningTextLatitude][!Redraw]
IfNotMatchAction=[!HideMeter WarningTextLatitude][!Redraw]

[WarningTextLongitude]
Meter=String
X=10
Y=210
FontFace=Segoe UI
StringStyle=Bold
FontSize=14
FontColor=255,255,255,255
AntiAlias=1
Text="Edite la Longitud en la configuración de la skin."
DynamicVariables=1
Measure=#Longitude#
IfMatch=^$
IfMatchAction=[!ShowMeter WarningTextLongitude][!Redraw]
IfNotMatchAction=[!HideMeter WarningTextLongitude][!Redraw]

[RoundTemp]
Measure=Calc
Formula=Round(Temp)
